services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - uploads:/app/uploads
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local

volumes:
  uploads:
