services:
  db:
    image: postgres:14
    container_name: postgres_db_${NODE_ENV}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_${NODE_ENV}:/var/lib/postgresql/data

volumes:
  postgres_data_development:
  postgres_data_test:
