/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PPlaylistIdImport } from './routes/p/$playlistId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PPlaylistIdRoute = PPlaylistIdImport.update({
  path: '/p/$playlistId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/p/$playlistId': {
      id: '/p/$playlistId'
      path: '/p/$playlistId'
      fullPath: '/p/$playlistId'
      preLoaderRoute: typeof PPlaylistIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$playlistId': typeof PPlaylistIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$playlistId': typeof PPlaylistIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/p/$playlistId': typeof PPlaylistIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$playlistId'
  id: '__root__' | '/' | '/p/$playlistId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PPlaylistIdRoute: typeof PPlaylistIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PPlaylistIdRoute: PPlaylistIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/p/$playlistId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/p/$playlistId": {
      "filePath": "p/$playlistId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
