name: Deploy to EC2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start docker if needed and pull latest code
        run: |
          sudo systemctl start docker || true

          cd music-player

          git pull origin main

      - name: Deploy Application with Docker
        run: |
          cd music-player
          docker-compose down
          docker-compose up -d --build

          docker system prune -f
