name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create backend .env
        run: |
          echo "NODE_ENV=prod" > backend/.env.prod
          echo "PORT=${{ secrets.PORT }}" >> backend/.env.prod
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}" >> backend/.env.prod
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env.prod

      - name: Create frontend .env
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > frontend/.env.local

      - name: Start docker if needed and pull latest code
        run: |
          sudo systemctl start docker || true
          git pull origin main

      - name: Deploy Backend
        run: |
          docker-compose up -d --no-deps --build backend

      - name: Deploy Frontend
        run: |
          docker-compose up -d --no-deps --build frontend

      - name: Verify deployment
        run: |
          echo "Checking services status:"
          docker-compose ps

      - name: Cleanup old images
        run: |
          docker image prune -f --filter "dangling=true"

      - name: Log deployment result
        if: always()
        run: |
          echo "Deployment finished with status: ${{ job.status }}"
          echo "Recent logs:"
          docker-compose logs --tail=50
